<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;

class TAdminPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = array(
            array(
                "id" => 105,
                "name" => "Income",
                "guard_name" => "web",
                "permission_key" => "accounts-management",
                "group_name" => "Accounts Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 104,
                "name" => "Accounts Management",
                "guard_name" => "web",
                "permission_key" => "accounts-management",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 103,
                "name" => "Pricing Plan Delete btn",
                "guard_name" => "web",
                "permission_key" => "pricing-plan-delete-btn",
                "group_name" => 'Pricing Plan',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 102,
                "name" => "Pricing Plan Edit btn",
                "guard_name" => "web",
                "permission_key" => "pricing-plan-edit-btn",
                "group_name" => 'Pricing Plan',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 101,
                "name" => "Pricing Plan Add btn",
                "guard_name" => "web",
                "permission_key" => "pricing-plan-add-btn",
                "group_name" => 'Pricing Plan',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 100,
                "name" => "Add Listing Form Delete btn",
                "guard_name" => "web",
                "permission_key" => "add-listing-form-delete-btn",
                "group_name" => 'Business Settings',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 99,
                "name" => "Add Listing Form Management",
                "guard_name" => "web",
                "permission_key" => "add-listing-form-management",
                "group_name" => 'Business Settings',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 98,
                "name" => "Pricing Plan",
                "guard_name" => "web",
                "permission_key" => "pricing-plan",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 97,
                "name" => "Privacy Policy",
                "guard_name" => "web",
                "permission_key" => "privacy-policy",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-03-20 10:20:37",
                "updated_at" => "2025-03-20 10:20:37",
            ),
            array(
                "id" => 96,
                "name" => "Reviews List btn",
                "guard_name" => "web",
                "permission_key" => "reviews-list-btn",
                "group_name" => 'Customer Management',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-17 10:20:37",
                "updated_at" => "2025-02-17 10:20:37",
            ),
            array(
                "id" => 95,
                "name" => "Apps Terms and Conditions",
                "guard_name" => "web",
                "permission_key" => "apps-terms-and-conditions",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:32:05",
                "updated_at" => "2025-01-30 10:32:05",
            ),
            array(
                "id" => 94,
                "name" => "Business Note",
                "guard_name" => "web",
                "permission_key" => "business-note",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:32:05",
                "updated_at" => "2025-01-30 10:32:05",
            ),
            array(
                "id" => 93,
                "name" => "Business List",
                "guard_name" => "web",
                "permission_key" => "business-list",
                "group_name" => 'Customer Management',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-17 10:20:37",
                "updated_at" => "2025-02-17 10:20:37",
            ),
            array(
                "id" => 92,
                "name" => "contact creed delete btn",
                "guard_name" => "web",
                "permission_key" => "contact-creed-delete-btn",
                "group_name" => 'contact creed',
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-17 10:20:37",
                "updated_at" => "2025-02-17 10:20:37",
            ),
            array(
                "id" => 91,
                "name" => "contact creed",
                "guard_name" => "web",
                "permission_key" => "contact-creed",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => 4,
                "created_at" => "2025-02-17 10:20:37",
                "updated_at" => "2025-02-17 10:20:37",
            ),
            array(
                "id" => 52,
                "name" => "subscription plan",
                "guard_name" => "web",
                "permission_key" => "subscription-plan",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:32:05",
                "updated_at" => "2025-01-30 10:32:05",
            ),
            array(
                "id" => 51,
                "name" => "about",
                "guard_name" => "web",
                "permission_key" => "about",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:20:37",
                "updated_at" => "2025-01-30 10:20:37",
            ),
            array(
                "id" => 50,
                "name" => "permission",
                "guard_name" => "web",
                "permission_key" => "permission",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:20:10",
                "updated_at" => "2025-01-30 10:20:10",
            ),
            array(
                "id" => 49,
                "name" => "role",
                "guard_name" => "web",
                "permission_key" => "role",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:19:55",
                "updated_at" => "2025-01-30 10:19:55",
            ),
            array(
                "id" => 48,
                "name" => "admin user",
                "guard_name" => "web",
                "permission_key" => "admin-user",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:19:37",
                "updated_at" => "2025-01-30 10:19:37",
            ),
            array(
                "id" => 47,
                "name" => "archieve list",
                "guard_name" => "web",
                "permission_key" => "archieve-list",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:19:18",
                "updated_at" => "2025-01-30 10:19:18",
            ),
            array(
                "id" => 46,
                "name" => "customer list",
                "guard_name" => "web",
                "permission_key" => "customer-list",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-30 10:18:09",
                "updated_at" => "2025-01-30 10:18:09",
            ),
            array(
                "id" => 31,
                "name" => "affliations",
                "guard_name" => "web",
                "permission_key" => "affliations",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:30:15",
                "updated_at" => "2025-01-29 02:30:15",
            ),
            array(
                "id" => 30,
                "name" => "restaurant",
                "guard_name" => "web",
                "permission_key" => "restaurant",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:30:02",
                "updated_at" => "2025-01-29 02:30:02",
            ),
            array(
                "id" => 29,
                "name" => "business tags",
                "guard_name" => "web",
                "permission_key" => "business-tags",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:29:43",
                "updated_at" => "2025-01-29 02:29:43",
            ),
            array(
                "id" => 28,
                "name" => "business subcategory",
                "guard_name" => "web",
                "permission_key" => "business-subcategory",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:29:25",
                "updated_at" => "2025-01-29 02:29:25",
            ),
            array(
                "id" => 27,
                "name" => "business category",
                "guard_name" => "web",
                "permission_key" => "business-category",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:29:14",
                "updated_at" => "2025-01-29 02:29:14",
            ),
            array(
                "id" => 25,
                "name" => "creed tags",
                "guard_name" => "web",
                "permission_key" => "creed-tags",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:28:44",
                "updated_at" => "2025-01-29 02:28:44",
            ),
            array(
                "id" => 26,
                "name" => "business type",
                "guard_name" => "web",
                "permission_key" => "business-type",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:29:01",
                "updated_at" => "2025-01-29 02:29:01",
            ),
            array(
                "id" => 24,
                "name" => "dashboard two",
                "guard_name" => "web",
                "permission_key" => "dashboard-two",
                "group_name" => "Dashboard",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 02:21:59",
                "updated_at" => "2025-01-29 02:21:59",
            ),
            array(
                "id" => 22,
                "name" => "Database Backup",
                "guard_name" => "web",
                "permission_key" => "db-backup",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 01:04:41",
                "updated_at" => "2025-01-29 01:04:41",
            ),
            array(
                "id" => 23,
                "name" => "dashboard one",
                "guard_name" => "web",
                "permission_key" => "dashboard-one",
                "group_name" => "Dashboard",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 01:05:03",
                "updated_at" => "2025-01-29 01:05:03",
            ),
            array(
                "id" => 21,
                "name" => "Import CSV",
                "guard_name" => "web",
                "permission_key" => "import-csv",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 01:04:31",
                "updated_at" => "2025-01-29 01:04:31",
            ),
            array(
                "id" => 13,
                "name" => "Dashboard",
                "guard_name" => "web",
                "permission_key" => "dashboard",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => 1,
                "created_at" => "2025-01-28 23:47:33",
                "updated_at" => "2025-01-28 23:47:33",
            ),
            array(
                "id" => 17,
                "name" => "Customer Management",
                "guard_name" => "web",
                "permission_key" => "customer",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => 3,
                "created_at" => "2025-01-29 01:02:25",
                "updated_at" => "2025-01-29 01:02:25",
            ),
            array(
                "id" => 18,
                "name" => "Business Settings",
                "guard_name" => "web",
                "permission_key" => "business-settings",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => 2,
                "created_at" => "2025-01-29 01:02:40",
                "updated_at" => "2025-01-29 01:02:40",
            ),
            array(
                "id" => 19,
                "name" => "User Management",
                "guard_name" => "web",
                "permission_key" => "user",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 01:03:57",
                "updated_at" => "2025-01-29 01:03:57",
            ),
            array(
                "id" => 20,
                "name" => "Company Info ",
                "guard_name" => "web",
                "permission_key" => "company-info",
                "group_name" => NULL,
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-01-29 01:04:10",
                "updated_at" => "2025-01-29 01:04:10",
            ),
            array(
                "id" => 53,
                "name" => "creed tags add btn",
                "guard_name" => "web",
                "permission_key" => "creed-tags-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:56:45",
                "updated_at" => "2025-02-06 03:56:45",
            ),
            array(
                "id" => 54,
                "name" => "creed tags edit btn",
                "guard_name" => "web",
                "permission_key" => "creed-tags-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:56:56",
                "updated_at" => "2025-02-06 03:56:56",
            ),
            array(
                "id" => 55,
                "name" => "creed tags delete btn",
                "guard_name" => "web",
                "permission_key" => "creed-tags-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:57:07",
                "updated_at" => "2025-02-06 03:57:07",
            ),
            array(
                "id" => 56,
                "name" => "business type add btn",
                "guard_name" => "web",
                "permission_key" => "business-type-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:57:37",
                "updated_at" => "2025-02-06 03:57:37",
            ),
            array(
                "id" => 57,
                "name" => "business type edit btn",
                "guard_name" => "web",
                "permission_key" => "business-type-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:57:47",
                "updated_at" => "2025-02-06 03:57:47",
            ),
            array(
                "id" => 58,
                "name" => "business type delete btn",
                "guard_name" => "web",
                "permission_key" => "business-type-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:58:00",
                "updated_at" => "2025-02-06 03:58:00",
            ),
            array(
                "id" => 59,
                "name" => "business category add btn",
                "guard_name" => "web",
                "permission_key" => "business-category-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:58:23",
                "updated_at" => "2025-02-06 03:58:23",
            ),
            array(
                "id" => 60,
                "name" => "business category edit btn",
                "guard_name" => "web",
                "permission_key" => "business-category-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:58:34",
                "updated_at" => "2025-02-06 03:58:34",
            ),
            array(
                "id" => 61,
                "name" => "business category delete btn",
                "guard_name" => "web",
                "permission_key" => "business-category-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:58:46",
                "updated_at" => "2025-02-06 03:58:46",
            ),
            array(
                "id" => 62,
                "name" => "business subcategory add btn",
                "guard_name" => "web",
                "permission_key" => "business-subcategory-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 03:59:17",
                "updated_at" => "2025-02-06 03:59:17",
            ),
            array(
                "id" => 63,
                "name" => "business subcategory edit btn",
                "guard_name" => "web",
                "permission_key" => "business-subcategory-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:01:11",
                "updated_at" => "2025-02-06 04:01:11",
            ),
            array(
                "id" => 64,
                "name" => "business subcategory delete btn",
                "guard_name" => "web",
                "permission_key" => "business-subcategory-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:01:51",
                "updated_at" => "2025-02-06 04:02:03",
            ),
            array(
                "id" => 65,
                "name" => "business tags add btn",
                "guard_name" => "web",
                "permission_key" => "business-tags-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:02:27",
                "updated_at" => "2025-02-06 04:02:27",
            ),
            array(
                "id" => 66,
                "name" => "business tags edit btn",
                "guard_name" => "web",
                "permission_key" => "business-tags-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:02:38",
                "updated_at" => "2025-02-06 04:02:38",
            ),
            array(
                "id" => 67,
                "name" => "business tags delete btn",
                "guard_name" => "web",
                "permission_key" => "business-tags-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:02:49",
                "updated_at" => "2025-02-06 04:02:49",
            ),
            array(
                "id" => 68,
                "name" => "restaurant add btn",
                "guard_name" => "web",
                "permission_key" => "restaurant-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:03:10",
                "updated_at" => "2025-02-06 04:03:10",
            ),
            array(
                "id" => 69,
                "name" => "restaurant edit btn",
                "guard_name" => "web",
                "permission_key" => "restaurant-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:03:21",
                "updated_at" => "2025-02-06 04:03:21",
            ),
            array(
                "id" => 70,
                "name" => "restaurant delete btn",
                "guard_name" => "web",
                "permission_key" => "restaurant-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:03:31",
                "updated_at" => "2025-02-06 04:03:31",
            ),
            array(
                "id" => 71,
                "name" => "affliations add btn",
                "guard_name" => "web",
                "permission_key" => "affliations-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:03:59",
                "updated_at" => "2025-02-06 04:03:59",
            ),
            array(
                "id" => 72,
                "name" => "affliations edit btn",
                "guard_name" => "web",
                "permission_key" => "affliations-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:04:10",
                "updated_at" => "2025-02-06 04:04:10",
            ),
            array(
                "id" => 73,
                "name" => "affliations delete btn",
                "guard_name" => "web",
                "permission_key" => "affliations-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:04:30",
                "updated_at" => "2025-02-06 04:04:30",
            ),
            array(
                "id" => 74,
                "name" => "subscription plan add btn",
                "guard_name" => "web",
                "permission_key" => "subscription-plan-add-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:05:07",
                "updated_at" => "2025-02-06 04:05:07",
            ),
            array(
                "id" => 75,
                "name" => "subscription plan edit btn",
                "guard_name" => "web",
                "permission_key" => "subscription-plan-edit-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:05:28",
                "updated_at" => "2025-02-06 04:05:28",
            ),
            array(
                "id" => 76,
                "name" => "subscription plan delete btn",
                "guard_name" => "web",
                "permission_key" => "subscription-plan-delete-btn",
                "group_name" => "Business Settings",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:05:45",
                "updated_at" => "2025-02-06 04:05:45",
            ),
            array(
                "id" => 77,
                "name" => "customers list add btn",
                "guard_name" => "web",
                "permission_key" => "customers-list-add-btn",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:06:20",
                "updated_at" => "2025-02-06 04:06:20",
            ),
            array(
                "id" => 78,
                "name" => "customers list edit btn",
                "guard_name" => "web",
                "permission_key" => "customers-list-edit-btn",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:06:30",
                "updated_at" => "2025-02-06 04:06:30",
            ),
            array(
                "id" => 79,
                "name" => "customers list delete btn",
                "guard_name" => "web",
                "permission_key" => "customers-list-delete-btn",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:06:44",
                "updated_at" => "2025-02-06 04:06:44",
            ),
            array(
                "id" => 80,
                "name" => "archieve list retrieve btn",
                "guard_name" => "web",
                "permission_key" => "archieve-list-retrieve-btn",
                "group_name" => "Customer Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:12:07",
                "updated_at" => "2025-02-06 04:12:07",
            ),

            array(
                "id" => 82,
                "name" => "admin user add btn",
                "guard_name" => "web",
                "permission_key" => "admin-user-add-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:13:20",
                "updated_at" => "2025-02-06 04:13:20",
            ),
            array(
                "id" => 83,
                "name" => "admin user edit btn",
                "guard_name" => "web",
                "permission_key" => "admin-user-edit-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:13:29",
                "updated_at" => "2025-02-06 04:13:29",
            ),
            array(
                "id" => 84,
                "name" => "admin user delete btn",
                "guard_name" => "web",
                "permission_key" => "admin-user-delete-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:13:39",
                "updated_at" => "2025-02-06 04:13:39",
            ),
            array(
                "id" => 85,
                "name" => "roles add btn",
                "guard_name" => "web",
                "permission_key" => "roles-add-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:15:16",
                "updated_at" => "2025-02-06 04:15:16",
            ),
            array(
                "id" => 86,
                "name" => "roles edit btn",
                "guard_name" => "web",
                "permission_key" => "roles-edit-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:15:28",
                "updated_at" => "2025-02-06 04:15:28",
            ),
            array(
                "id" => 87,
                "name" => "roles delete btn",
                "guard_name" => "web",
                "permission_key" => "roles-delete-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:15:38",
                "updated_at" => "2025-02-06 04:15:38",
            ),
            array(
                "id" => 88,
                "name" => "permissions add btn",
                "guard_name" => "web",
                "permission_key" => "permissions-add-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:16:04",
                "updated_at" => "2025-02-06 04:16:04",
            ),
            array(
                "id" => 89,
                "name" => "permissions edit btn",
                "guard_name" => "web",
                "permission_key" => "permissions-edit-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:16:15",
                "updated_at" => "2025-02-06 04:16:15",
            ),
            array(
                "id" => 90,
                "name" => "permissions delete btn",
                "guard_name" => "web",
                "permission_key" => "permissions-delete-btn",
                "group_name" => "User Management",
                "description" => NULL,
                "priority_id" => NULL,
                "created_at" => "2025-02-06 04:16:29",
                "updated_at" => "2025-02-06 04:16:29",
            ),
        );


        DB::table('permissions')->insert($permissions);

        Artisan::call('permission:cache-reset');
    }
}
